# Kshitij Data

client_id = "39TZQYIFTG-100"
secret_key = "U0IRMUCHBY"
redirect_uri = "https://ec433e45526d.ngrok-free.app/fyers/callback"
response_type = "code"  
state = "sample_state"
access_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIiwieDoyIl0sImF0X2hhc2giOiJnQUFBQUFCcEtSeWpmN1NrUG0zUkhES1ZxcHlqejB1S25DS0pXaXgzYzl1OVY2SDM4MTJKbHd4ZzZJZnUzamdZRGRWakkzZmE5T2hjTTFfZlBjVGVreHBSRGZQVHZzZ1RoUG0zY19nSVNuSXJkdXpjNTA0XzFqcz0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiJlNTI5ZmRlY2IxNTQzNDcxYTZhMzQ3ZjdjYzg1ZTczMGQzNDZmNWE5ZjFjYzM4ZWUyZWRmZDQwMSIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiWEswMzA2MSIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzY0Mzc2MjAwLCJpYXQiOjE3NjQzMDE5ODcsImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc2NDMwMTk4Nywic3ViIjoiYWNjZXNzX3Rva2VuIn0.phRHIsOZ_quV95KF09Uf42TCBtSMWYmsXFpjy8Tti3U"